---
contentType: page
useComponent: true
slug: application-homepage
head:
  contentType: head
  title: Application overview listing
breadcrumb:
- contentType: link
  text: Overview
  url: "/"
- contentType: link
  text: Applications
  url: "/"
hero:
  modifiers: border
  title:
    contentType: title
    title: Space license applications
  infoGrid:
  - contentType: heading
    text: 1 new, 4 pending
    type: p
    modifiers: lede
  - contentType: heading
    text: <a href="#">View completed applications</a>
    type: p
    modifiers: lede
filters:
- label: Filter
  id: filter-by
  options:
  - label: Launch Date - soonest
    value: launch-date
  - label: Launch Date - furthest
    value: launch-date
- label: Sort
  id: sort-by
  options:
  - label: Alphabetically A - Z
    value: a-z
  - label: Alphabetically Z - A
    value: z-a
listing:
- heading:
    text: New
    type: h2
    modifiers: heading-large
  list:
  - heading:
      text: Inmarsat
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Rachel Jeffries
    label:
      tag: I-OL
      class: bg-pink
- heading:
    text: Pending
    type: h2
    modifiers: heading-large
  list:
  - status: 3 UPDATES
    heading:
      text: Inmarsat
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    - text: Launch Name
      value: LM1256
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Rachel Jeffries
    label:
      tag: RCS
      class: bg-green
  - heading:
      text: Inmarsat
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    - text: Launch Name
      value: LM1256
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Rachel Jeffries
    label:
      tag: LS
      class: bg-orange
  - heading:
      text: Inmarsat
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Rachel Jeffries
    label:
      tag: I-OL
      class: bg-pink
  - heading:
      text: Lockheed Martin
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Rachel Jeffries
    label:
      tag: LS
      class: bg-orange
  - heading:
      text: Lockheed Martin
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Rachel Jeffries
    label:
      tag: SP
      class: bg-brown
