---
contentType: page
useComponent: true
slug: test
head:
  contentType: head
  title: Test page
hero:
  modifiers: bg-dark bg-blue
  breadcrumb:
  - contentType: link
    text: Space Agency UK
    url: "/"
  - contentType: link
    text: Applications
    url: "/application-overview/"
  - contentType: link
    text: Application 11021411
  licenceType:
  - contentType: heading
    text: IN-ORBIT LICENCE
    type: p
    modifiers: heading-medium badge badge--large bg-pink
  - contentType: heading
    text: "<span class='quiet'>Ref: </span> 11021411"
    type: p
    modifiers: heading-medium float-right
  title:
    contentType: title
    title: Inmarsat Application
    modifiers: spacing-bottom--tight
    # subTitle: this is a smaller bit of content to support the main title
  infoGrid:
  - contentType: heading
    text: "<span class='quiet'>Satellite number: </span> Gh341211b"
    type: p
    modifiers: heading-small
  - contentType: heading
    text: "<span class='quiet'>Submitted: </span>4 June 2017"
    type: p
    modifiers: heading-small
  - contentType: heading
    text: "<span class='quiet'>Status: </span> Partially Complete"
    type: p
    modifiers: heading-small
  licenceTypeGrid:
    heading:
      text: Licence type
      type: p
      modifiers: heading-small padding-bottom--tight spacing-bottom--single border bottom-border mr-5
    items:
    - contentType: boolean
      name: license-type
      type: checkbox
      modifiers: multiple-choice--inline
      inputs:
      - id: ieurhferf
        checked: true
        value: Operations
      - id: ieurhferf12
        checked: true
        value: Emergency operations
      - id: ieurhferf21
        checked: true
        value: Temporary operations
  heroLinks:
    links:
      modifiers: list-arrow list-arrow--dark
      list:
      - url: "#finance"
        text: Finance
      - url: "#frequency"
        text: Frequency
      - url: "#insurance"
        text: Insurance
      - url: "#technical"
        text: Technical
      - url: "#legal"
        text: Legal
      - url: "#political"
        text: Political
        icon:
          label: tick
          modifiers: icon-tick-white
      - url: "#mod"
        text: MOD
    notice:
      contentType: heading
      text: "<span class='quiet'>Launch Date</span> <br/>4 June 2018"
      type: h2
      modifiers: badge bg-pink heading-small
    heading:
      contentType: heading
      text: License overview
      type: h2
      modifiers: heading-small spacing-top--tight
  # synopsis:
  #   contentType: longform
  #   intro: Submission overview
  #   modifiers: heading-medium
  #   text: "<p class='lede'>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
  #     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
  #     minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
  #     commodo consequat.</p>"
content:
- contentType: heading
  text: Applications sections
  type: h2
  modifiers: heading-large
- contentType: listing
  columns: 2
  content:
  - contentType: tile
    id: finance
    heading:
      contentType: heading
      text: Finance
      type: p
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "3<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '/application-overview/finance'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: p
      modifiers: heading-medium
  - contentType: tile
    id: frequency
    heading:
      contentType: heading
      text: Frequency
      type: p
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "2<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      fullWidth: true
      url: '/application-overview/frequency'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: Insurance
      type: p
      modifiers: heading-large
    id: insurance
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "2<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '/application-overview/insurance'
      label: View
      gridModifier: column-full
      modifiers: button--half-width
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: Technical
      type: p
      modifiers: heading-large
    id: technical
    updates:
      url: "/updates"
      text: 2 updates
      modifiers: bg-blue badge--fixed badge--top
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "1<br/><span class='quiet'>Attachment</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '/application-overview/technical'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: Legal
      type: p
      modifiers: heading-large
    id: legal
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "8<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      fullWidth: true
      url: '/application-overview/frequency'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: Political
      icon:
        label: tick
        modifiers: icon-tick-green icon--large
      type: p
      modifiers: heading-large
    id: political
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "6<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '/application-overview/insurance'
      label: View
      gridModifier: column-full
      modifiers: button--half-width
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: MOD
      type: p
      modifiers: heading-large
    id: mod
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "0<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '/application-overview/technical'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: p
      modifiers: heading-medium
- contentType: heading
  text: Operator Contact
  type: h2
  modifiers: heading-medium
- contentType: heading
  text: James Smart
  type: p
  modifiers: heading-small border bottom-border padding-bottom--tight
- contentType: infoGrid
  grid:
  - contentType: heading
    text: "<a href='mailto:james@inmarsat.com'>email: james@inmarsat.com</a>"
    type: p
  - contentType: heading
    text: "phone: 0117 801735"
    type: p
  - contentType: heading
    text: "mobile: +44 7882281628"
    type: p
- contentType: infoGrid
  grid:
  - text: "address: 80 Gloucester Road, London, WC2 2BA"
    type: p
    gridModifier: column-full
