---
contentType: page
useComponent: true
slug: test
head:
  contentType: head
  title: Test page
hero:
  modifiers: bg--dark bg--blue
  breadcrumb:
  - contentType: link
    text: Space Agency UK
    url: "/"
  - contentType: link
    text: Applications
    url: "/application-overview/"
  - contentType: link
    text: Application 11021411
  licenceType:
  - contentType: heading
    text: Orbital licence
    type: p
    modifiers: heading-medium badge badge--large bg-pink
  - contentType: heading
    text: "<span class='quiet'>Ref: </span> 11021411"
    type: p
    modifiers: heading-medium float-right
  title:
    contentType: title
    title: Inmarsat Application
    subTitle: this is a smaller bit of content to support the main title
  infoGrid:
  - contentType: heading
    text: "<span class='quiet'>Satellite number: </span> Gh341211b"
    type: h3
    modifiers: heading-small
  - contentType: heading
    text: "<span class='quiet'>Submitted: </span>4 June 2017"
    type: h3
    modifiers: heading-small
  - contentType: heading
    text: "<span class='quiet'>Status: </span> Partially Complete"
    type: h3
    modifiers: heading-small
  synopsis:
    contentType: longform
    intro: Submission overview
    modifiers: heading-medium
    text: "<p class='lede'>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat.</p>"
content:
- contentType: heading
  text: Applications sections
  type: h2
  modifiers: heading-large
- contentType: listing
  columns: 2
  content:
  - contentType: tile
    heading:
      contentType: heading
      text: Finance
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/finance'
      label: View
      modifiers: button--full-width
  - contentType: tile
    heading:
      contentType: heading
      text: Frequency
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/frequency'
      label: View
      modifiers: button--full-width
  - contentType: tile
    heading:
      contentType: heading
      text: Insurance
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/insurance'
      label: View
      modifiers: button--full-width
  - contentType: tile
    heading:
      contentType: heading
      text: Technical
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/technical'
      label: View
      modifiers: button--full-width
