---
contentType: page
useComponent: true
slug: application-homepage

head:
  contentType: head
  title: Application overview listing
masthead:
  utility:
    links:
    - text: Settings
      url: "/application-overview/new-member"
breadcrumb:
- contentType: link
  text: Overview
  url: "/"
- contentType: link
  text: Applications
  url: "/"
hero:
  modifiers: border padding-top--single spacing-bottom--flush
  infoGrid:
  - contentType: heading
    text: Your licence cases
    type: p
  - contentType: heading
    text: <a href="#">View completed applications</a>
    type: p
    modifiers: float-right
listing:
- heading:
    text: New (2)
    type: h2
    modifiers: heading-large
  list:
  - status:
      label: New
      modifiers: bg-orange dark
    heading:
      text: Satellite operator 2
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Dave Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: John Terry
    label:
      tag: In-orbit
      class: bg-orange
  - status:
      label: New
      modifiers: bg-pink dark
    heading:
      text: Satellite operator 1
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Dave Francis
    label:
      tag: In-orbit
      class: bg-pink
- heading:
    text: Your applications (2 with updates)
    type: h2
    modifiers: heading-large
  filters:
    blocks:
    - label: Filter
      id: filter-by
      options:
      - label: Select
        value: please-select
      - label: Lorem ipsum
        value: launch-date
    - label: Sort
      id: sort-by
      options:
      - label: Alphabetically A - Z
        value: a-z
      - label: Alphabetically Z - A
        value: z-a
  list:
  - status:
      label: 2 updates
      modifiers: bg-fuschia
    heading:
      text: Satellite operator 1
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    - text: Launch Name
      value: LM1256
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Dave Francis
    label:
      tag: Range
      class: bg-green
  - status:
      label: 4 updates
      modifiers: bg-fuschia
    heading:
      text: Satellite operator 1
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    - text: Launch Name
      value: LM1256
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Dave Francis
    label:
      tag: Launch
      class: bg-orange
  - heading:
      text: Satellite operator 1
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Dave Francis
    label:
      tag: In-orbit
      class: bg-pink
  - heading:
      text: Satellite operator 3
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Dave Francis
    label:
      tag: Launch
      class: bg-orange
  - heading:
      text: Satellite operator 3
      type: h3
      modifiers: heading-medium spacing-top--flush
    items:
    - text: Applicant name
      value: Richard Branson
    appStatus: Awaiting Action
    url: "/application-overview"
    reference: 62dsffg7238djuju4756
    updated: 10th March 2018
    updater: Dave Francis
    label:
      tag: Space port
      class: bg-brown
