---
contentType: page
useComponent: true
slug: application-overview
head:
  contentType: head
  title: Application overview
masthead:
  utility:
    links:
    - text: Notifications
      url: "/notifications"
      notification: 3
    - text: Settings
      url: "/application-overview/new-member"
hero:
  modifiers: bg-dark bg-blue
  breadcrumb:
  - contentType: link
    text: Space Agency UK
    url: "/"
  - contentType: link
    text: Applications
    url: "/application-overview/"
  - contentType: link
    text: Application 11021411
  licenceType:
  - contentType: heading
    text: IN-ORBIT LICENCE
    type: p
    modifiers: heading-medium badge badge--large bg-pink
  - contentType: heading
    text: "<span class='quiet'>Ref: </span> 11021411"
    type: p
    modifiers: heading-medium float-right
  title:
    contentType: title
    title: Satellite operator 1
    modifiers: spacing-bottom--tight
    # subTitle: this is a smaller bit of content to support the main title
  infoGrid:
  - contentType: heading
    text: "<span class='quiet'>Satellite number: </span> Gh341211b"
    type: p
    modifiers: heading-small
  - contentType: heading
    text: "<span class='quiet'>Submitted: </span>4 June 2017"
    type: p
    modifiers: heading-small
  - contentType: heading
    text: "<span class='quiet'>Status: </span> Partially Complete"
    type: p
    modifiers: heading-small
  licenceTypeGrid:
    heading:
      text: Licence type
      type: p
      modifiers: heading-small padding-bottom--tight spacing-bottom--single border bottom-border mr-5
    items:
    - contentType: boolean
      name: license-type
      type: checkbox
      modifiers: multiple-choice--inline
      inputs:
      - id: ieurhferf
        checked: true
        value: Operations
      - id: ieurhferf12
        checked: true
        value: Emergency operations
      - id: ieurhferf21
        checked: true
        value: Temporary operations
  heroLinks:
    links:
      modifiers: list-arrow list-arrow--dark
      list:
      - url: "#finance"
        text: Finance
      - url: "/application-overview/frequency"
        text: Frequency
      - url: "#insurance"
        text: Insurance
      - url: "/application-overview/technical"
        text: Technical
      - url: "#legal"
        text: Legal
      - url: "#political"
        text: Political
        icon:
          label: tick
          modifiers: icon-tick-white
      - url: "#mod"
        text: MOD
    notice:
      contentType: heading
      text: "<span class='quiet'>Launch Date</span> <br/>4 June 2018"
      type: h2
      modifiers: badge bg-pink-40 heading-small
    heading:
      contentType: heading
      text: License overview
      type: h2
      modifiers: heading-small spacing-top--tight
  synopsisCollapsible:
    contentType: heading
    text: "<a href='/application-overview/technical/all-attachments'>View all attachments</a>"
    type: p
    modifiers: spacing-top--single
  # synopsis:
  #   contentType: longform
  #   intro: Submission overview
  #   modifiers: heading-medium
  #   text: "<p class='lede'>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
  #     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
  #     minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
  #     commodo consequat.</p>"
content:
- contentType: collapsiblepanel
  commentBlock:
    limit: 3
    modifiers: spacing-bottom--single
    collapsible: true
    tabs:
    - label: Satellite operator 1 notes (1)
      id: notes-open
    - label: My notes (2)
      id: notes-private
    notice:
      checkbox:
        name: priority-level
        type: checkbox
        fieldModifiers: float-right d-inline-block
        inputs:
        - id: juu7gg4gf33f
          value: High priority
    source:
      legend: Comment source
      fieldsetModifiers: inline
      items:
      - contentType: boolean
        name: second-radio-item
        type: radio
        inputs:
        - id: dfgh89dfgh
          value: Comment
          checked: true
        - id: hjdktlhivm67
          value: Phone call
        - id: llojef6
          value: Email
    assignees:
      label: Assign to
      # supporting: Select multiple by pressing shift and clicking
      id: assignees-question-2
      # multiple: true
      # data: data-assign
      options:
      - label: Please select
        value: ''
      - label: Joel Harris
        value: sfkhwer87hkj34h
        selected: true
      - label: Luke Wotten
        value: sfkhwesdtjsdfhgqw
      - label: Jon Smith
        value: adwty5nnkv08b
      - label: Dave Stringer
        value: jfmfuue67tg3f
      - label: Aimee Brace
        value: lvm08jjetffs
        selected: true
      - label: Alex Hobbs
        value: kfj789dbv
      - label: Tom Foster
        value: 15rdcsb
        selected: true
    deadline:
      legend: Set deadline
      calendar: true
      items:
      - label: Day
        id: 3245
        name: deadline-day
        modifiers: form-group-day
        type: number
        attr:
          key: pattern
          value: '[0-9]*'
      - label: Month
        id: 43563456
        name: deadline-month
        modifiers: form-group-month
        type: number
        attr:
          key: pattern
          value: '[0-9]*'
      - label: Year
        id: 45674567
        name: deadline-year
        modifiers: form-group-year
        type: number
        attr:
          key: pattern
          value: '[0-9]*'
    button:
      label: Add comment
    fileupload:
      label: Upload attachment
      modifiers: file-upload
      id: file-upload-2
      shimmed: true
    comments:
    - byline:
        modifiers: spacing-bottom--single
        name:
          text: Simon Griffith
          type: h3
          modifiers: heading-small
        url: "/rachel"
        date:
          date: 10.04am 22nd March 2018
          datetime: '2018-03-26T19:34:15+00:00'
        icon:
          label: account
          modifiers: icon-account
      text: "<p>Please can </p><p>Nemo enim ipsam voluptatem quia voluptas sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>"
      documents:
      - text: Disposal diagram
        url: "/pdfs/disposal-discovery.pdf"
        type: .pdf
        supporting: (12mb)
      deadline:
        text: "<span class='quiet'>Deadline</span><br/>4 June 2018"
        type: p
        modifiers: heading-small
      assignees:
        text: "<span class='quiet'>Assigned to</span><br/>Joel Hobbs"
        type: p
        modifiers: heading-small
- contentType: heading
  text: Applications sections
  type: h2
  modifiers: heading-large
- contentType: listing
  columns: 2
  content:
  - contentType: tile
    id: finance
    heading:
      contentType: heading
      text: Finance
      type: p
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "3<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '#'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Dave Francis"
      type: p
      modifiers: heading-medium
  - contentType: tile
    id: frequency
    heading:
      contentType: heading
      text: Frequency
      type: p
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "2<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      fullWidth: true
      url: '/application-overview/frequency'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Dave Francis"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: Insurance
      type: p
      modifiers: heading-large
    id: insurance
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "2<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '#'
      label: View
      gridModifier: column-full
      modifiers: button--half-width
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Dave Francis"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: Technical
      type: p
      modifiers: heading-large
    id: technical
    updates:
      url: "#"
      text: 2 updates
      modifiers: bg-fuschia badge--fixed badge--top
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "1<br/><span class='quiet'>Attachment</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '/application-overview/technical'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Dave Francis"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: Legal
      type: p
      modifiers: heading-large
    id: legal
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "8<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      fullWidth: true
      url: '#'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Dave Francis"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: Political
      icon:
        label: tick
        modifiers: icon-tick-green icon--large
      type: p
      modifiers: heading-large
    id: political
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "6<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '#'
      label: View
      gridModifier: column-full
      modifiers: button--half-width
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Dave Francis"
      type: p
      modifiers: heading-medium
  - contentType: tile
    heading:
      contentType: heading
      text: MOD
      type: p
      modifiers: heading-large
    id: mod
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "0<br/><span class='quiet'>Attachments</span>"
      type: p
      modifiers: heading-medium
    - contentType: button
      url: '#'
      label: View
      modifiers: button--half-width
      gridModifier: column-full
    - contentType: divider
      modifiers: border border-bottom
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: p
      modifiers: heading-medium
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Dave Francis"
      type: p
      modifiers: heading-medium
- contentType: heading
  text: Operator Contact
  type: h2
  modifiers: heading-medium
- contentType: heading
  text: James Smart
  type: p
  modifiers: heading-small border bottom-border padding-bottom--tight
- contentType: infoGrid
  grid:
  - contentType: heading
    text: "<a href='mailto:james@Satellite-operator-1.com'>email: james@Satellite-operator-1.com</a>"
    type: p
  - contentType: heading
    text: "phone: 0117 801735"
    type: p
  - contentType: heading
    text: "mobile: +44 7882281628"
    type: p
- contentType: infoGrid
  grid:
  - text: "address: 80 Gloucester Road, London, WC2 2BA"
    type: p
    gridModifier: column-full
