---
contentType: page
useComponent: true
slug: test
head:
  contentType: head
  title: Test page
hero:
  modifiers: bg-dark bg-blue
  breadcrumb:
  - contentType: link
    text: Space Agency UK
    url: "/"
  - contentType: link
    text: Applications
    url: "/application-overview/"
  - contentType: link
    text: Application 11021411
  licenceType:
  - contentType: heading
    text: In-orbit licence
    type: p
    modifiers: heading-medium badge badge--large bg-pink
  - contentType: heading
    text: "<span class='quiet'>Ref: </span> 11021411"
    type: p
    modifiers: heading-medium float-right
  title:
    contentType: title
    title: Inmarsat Application
    # subTitle: this is a smaller bit of content to support the main title
  infoGrid:
  - contentType: heading
    text: "<span class='quiet'>Satellite number: </span> Gh341211b"
    type: h3
    modifiers: heading-small
  - contentType: heading
    text: "<span class='quiet'>Submitted: </span>4 June 2017"
    type: h3
    modifiers: heading-small
  - contentType: heading
    text: "<span class='quiet'>Status: </span> Partially Complete"
    type: h3
    modifiers: heading-small
  licenceTypeGrid:
    heading:
      text: Licence type
      type: h3
      modifiers: heading-small border-bottom spacing-bottom--single bottom-border-bg-white
    items:
    - contentType: boolean
      name: license-type
      type: checkbox
      modifiers: multiple-choice--inline
      inputs:
      - id: ieurhferf
        value: Launch & commissioning
      - id: ieurhferf12
        value: commissioning
      - id: ieurhferf21
        checked: true
        value: Operational
      - id: ieurhferfsfdg21
        value: Emergency
  heroLinks:
    links:
      modifiers: list-arrow list-arrow--dark
      list:
      - url: "#"
        text: Finance
      - url: "#"
        text: Frequency
      - url: "#"
        text: Frequency
      - url: "#"
        text: Frequency
      - url: "#"
        text: Frequency
      - url: "#"
        text: Frequency
    notice:
      contentType: heading
      text: "<span class='quiet'>Launch Date</span> <br/>4 June 2018"
      type: h2
      modifiers: badge bg-pink heading-small
    heading:
      contentType: heading
      text: License overview
      type: h2
      modifiers: heading-small spacing-top--tight
  # synopsis:
  #   contentType: longform
  #   intro: Submission overview
  #   modifiers: heading-medium
  #   text: "<p class='lede'>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
  #     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
  #     minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
  #     commodo consequat.</p>"
content:
- contentType: heading
  text: Applications sections
  type: h2
  modifiers: heading-large
- contentType: listing
  columns: 2
  content:
  - contentType: tile
    heading:
      contentType: heading
      text: Finance
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/finance'
      label: View
      modifiers: button--full-width
      gridModifier: column-full
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: h3
      modifiers: heading-small
  - contentType: tile
    heading:
      contentType: heading
      text: Frequency
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: button
      fullWidth: true
      url: '/application-overview/frequency'
      label: View
      modifiers: button--full-width
      gridModifier: column-full
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: h3
      modifiers: heading-small
  - contentType: tile
    heading:
      contentType: heading
      text: Insurance
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/insurance'
      label: View
      gridModifier: column-full
      modifiers: button--full-width
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: h3
      modifiers: heading-small
  - contentType: tile
    heading:
      contentType: heading
      text: Technical
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/technical'
      label: View
      modifiers: button--full-width
      gridModifier: column-full
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: h3
      modifiers: heading-small
  - contentType: tile
    heading:
      contentType: heading
      text: Legal
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: button
      fullWidth: true
      url: '/application-overview/frequency'
      label: View
      modifiers: button--full-width
      gridModifier: column-full
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: h3
      modifiers: heading-small
  - contentType: tile
    heading:
      contentType: heading
      text: Political
      icon: tick
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/insurance'
      label: View
      gridModifier: column-full
      modifiers: button--full-width
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: h3
      modifiers: heading-small
  - contentType: tile
    heading:
      contentType: heading
      text: MOD
      type: h3
      modifiers: heading-large
    grid:
    - contentType: heading
      text: "2 of 3<br/><span class='quiet'>Questions completed</span>"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "0 of 3<br/><span class='quiet'>Attachments reviewed</span>"
      type: h3
      modifiers: heading-small
    - contentType: button
      url: '/application-overview/technical'
      label: View
      modifiers: button--full-width
      gridModifier: column-full
    - contentType: heading
      text: "<span class='quiet'>Last updated</span><br/>10<sup>th</sup>March 2014"
      type: h3
      modifiers: heading-small
    - contentType: heading
      text: "<span class='quiet'>By</span><br/>Rachel Morris"
      type: h3
      modifiers: heading-small
- contentType: heading
  text: Operator Contact
  type: h2
  modifiers: heading-medium
- contentType: heading
  text: James Smart
  type: p
  modifiers: heading-small border-bottom border-bottom-bg-dark-grey
- contentType: infoGrid
  grid:
  - contentType: heading
    text: "<a href='mailto:james@inmarsat.com'>email: james@inmarsat.com</a>"
    type: p
  - contentType: heading
    text: "phone: 0117 801735"
    type: p
  - contentType: heading
    text: "mobile: +44 7882281628"
    type: p
