rules:
  property-sort-order: 0
  no-warn: 0
  class-name-format: 0
  single-line-per-selector: 2
  quotes: 2
  empty-line-between-blocks: 2
  mixins-before-declarations: 1
  indentation: 2
  no-duplicate-properties: 2
  space-after-comma: 2
  no-mergeable-selectors: 2
  no-color-literals: 1
  hex-notation: 2
  no-trailing-zero: 2
  leading-zero: 2
  space-after-colon: 2
  final-newline: 2
